// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOQ-JjrgFvffCuhsNF-t2djUghk6Lc15U',
    appId: '1:645505691758:web:d265a228f079081d79367f',
    messagingSenderId: '645505691758',
    projectId: 'habit-mvp-pro',
    authDomain: 'habit-mvp-pro.firebaseapp.com',
    storageBucket: 'habit-mvp-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5B2Kw6YwOevhfZqcXMSKKBGzGWEZmj9E',
    appId: '1:645505691758:android:be010b43fde4a51a79367f',
    messagingSenderId: '645505691758',
    projectId: 'habit-mvp-pro',
    storageBucket: 'habit-mvp-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRBopjXDyUTRqCUgOO6EjHQyZRTJ8pFI',
    appId: '1:645505691758:ios:663b955e2e78922479367f',
    messagingSenderId: '645505691758',
    projectId: 'habit-mvp-pro',
    storageBucket: 'habit-mvp-pro.firebasestorage.app',
    iosBundleId: 'com.example.habitMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzRBopjXDyUTRqCUgOO6EjHQyZRTJ8pFI',
    appId: '1:645505691758:ios:663b955e2e78922479367f',
    messagingSenderId: '645505691758',
    projectId: 'habit-mvp-pro',
    storageBucket: 'habit-mvp-pro.firebasestorage.app',
    iosBundleId: 'com.example.habitMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOQ-JjrgFvffCuhsNF-t2djUghk6Lc15U',
    appId: '1:645505691758:web:ae44b1a8afacb5a479367f',
    messagingSenderId: '645505691758',
    projectId: 'habit-mvp-pro',
    authDomain: 'habit-mvp-pro.firebaseapp.com',
    storageBucket: 'habit-mvp-pro.firebasestorage.app',
  );
}
